#!/bin/bash
export _JAVA_AWT_WM_NONREPARENTING=1
SILENT_JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"
java $SILENT_JAVA_OPTIONS -jar /opt/jremed/JREmenuEditor.jar